services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5433:5432

  server:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env

#TODO: don't forget to remove this (only use for debug) 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
  
