services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    # uncomment to test migration
    # ports:
    #   - 5432:5432 

  server:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:8080

volumes:
  postgres_data:
  
