// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package schema

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// AuthorizeGUID request
	AuthorizeGUID(ctx context.Context, guid string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetGUID request
	GetGUID(ctx context.Context, params *GetGUIDParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RefreshTokensWithBody request with any body
	RefreshTokensWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RefreshTokens(ctx context.Context, body RefreshTokensJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Unauthorize request
	Unauthorize(ctx context.Context, params *UnauthorizeParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) AuthorizeGUID(ctx context.Context, guid string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAuthorizeGUIDRequest(c.Server, guid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetGUID(ctx context.Context, params *GetGUIDParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetGUIDRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RefreshTokensWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRefreshTokensRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RefreshTokens(ctx context.Context, body RefreshTokensJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRefreshTokensRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Unauthorize(ctx context.Context, params *UnauthorizeParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUnauthorizeRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewAuthorizeGUIDRequest generates requests for AuthorizeGUID
func NewAuthorizeGUIDRequest(server string, guid string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "guid", runtime.ParamLocationPath, guid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetGUIDRequest generates requests for GetGUID
func NewGetGUIDRequest(server string, params *GetGUIDParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/get")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "access_token", runtime.ParamLocationHeader, params.AccessToken)
		if err != nil {
			return nil, err
		}

		req.Header.Set("access_token", headerParam0)

	}

	return req, nil
}

// NewRefreshTokensRequest calls the generic RefreshTokens builder with application/json body
func NewRefreshTokensRequest(server string, body RefreshTokensJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRefreshTokensRequestWithBody(server, "application/json", bodyReader)
}

// NewRefreshTokensRequestWithBody generates requests for RefreshTokens with any type of body
func NewRefreshTokensRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/refresh")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUnauthorizeRequest generates requests for Unauthorize
func NewUnauthorizeRequest(server string, params *UnauthorizeParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/unauthorize")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "access_token", runtime.ParamLocationHeader, params.AccessToken)
		if err != nil {
			return nil, err
		}

		req.Header.Set("access_token", headerParam0)

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// AuthorizeGUIDWithResponse request
	AuthorizeGUIDWithResponse(ctx context.Context, guid string, reqEditors ...RequestEditorFn) (*AuthorizeGUIDResponse, error)

	// GetGUIDWithResponse request
	GetGUIDWithResponse(ctx context.Context, params *GetGUIDParams, reqEditors ...RequestEditorFn) (*GetGUIDResponse, error)

	// RefreshTokensWithBodyWithResponse request with any body
	RefreshTokensWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RefreshTokensResponse, error)

	RefreshTokensWithResponse(ctx context.Context, body RefreshTokensJSONRequestBody, reqEditors ...RequestEditorFn) (*RefreshTokensResponse, error)

	// UnauthorizeWithResponse request
	UnauthorizeWithResponse(ctx context.Context, params *UnauthorizeParams, reqEditors ...RequestEditorFn) (*UnauthorizeResponse, error)
}

type AuthorizeGUIDResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *TokenPair
}

// Status returns HTTPResponse.Status
func (r AuthorizeGUIDResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AuthorizeGUIDResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetGUIDResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GUID
}

// Status returns HTTPResponse.Status
func (r GetGUIDResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetGUIDResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RefreshTokensResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TokenPair
}

// Status returns HTTPResponse.Status
func (r RefreshTokensResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RefreshTokensResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UnauthorizeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r UnauthorizeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UnauthorizeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// AuthorizeGUIDWithResponse request returning *AuthorizeGUIDResponse
func (c *ClientWithResponses) AuthorizeGUIDWithResponse(ctx context.Context, guid string, reqEditors ...RequestEditorFn) (*AuthorizeGUIDResponse, error) {
	rsp, err := c.AuthorizeGUID(ctx, guid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAuthorizeGUIDResponse(rsp)
}

// GetGUIDWithResponse request returning *GetGUIDResponse
func (c *ClientWithResponses) GetGUIDWithResponse(ctx context.Context, params *GetGUIDParams, reqEditors ...RequestEditorFn) (*GetGUIDResponse, error) {
	rsp, err := c.GetGUID(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetGUIDResponse(rsp)
}

// RefreshTokensWithBodyWithResponse request with arbitrary body returning *RefreshTokensResponse
func (c *ClientWithResponses) RefreshTokensWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RefreshTokensResponse, error) {
	rsp, err := c.RefreshTokensWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRefreshTokensResponse(rsp)
}

func (c *ClientWithResponses) RefreshTokensWithResponse(ctx context.Context, body RefreshTokensJSONRequestBody, reqEditors ...RequestEditorFn) (*RefreshTokensResponse, error) {
	rsp, err := c.RefreshTokens(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRefreshTokensResponse(rsp)
}

// UnauthorizeWithResponse request returning *UnauthorizeResponse
func (c *ClientWithResponses) UnauthorizeWithResponse(ctx context.Context, params *UnauthorizeParams, reqEditors ...RequestEditorFn) (*UnauthorizeResponse, error) {
	rsp, err := c.Unauthorize(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUnauthorizeResponse(rsp)
}

// ParseAuthorizeGUIDResponse parses an HTTP response from a AuthorizeGUIDWithResponse call
func ParseAuthorizeGUIDResponse(rsp *http.Response) (*AuthorizeGUIDResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AuthorizeGUIDResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest TokenPair
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseGetGUIDResponse parses an HTTP response from a GetGUIDWithResponse call
func ParseGetGUIDResponse(rsp *http.Response) (*GetGUIDResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetGUIDResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GUID
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseRefreshTokensResponse parses an HTTP response from a RefreshTokensWithResponse call
func ParseRefreshTokensResponse(rsp *http.Response) (*RefreshTokensResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RefreshTokensResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TokenPair
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseUnauthorizeResponse parses an HTTP response from a UnauthorizeWithResponse call
func ParseUnauthorizeResponse(rsp *http.Response) (*UnauthorizeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UnauthorizeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
