// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package schema

// AccessToken A JWT Token consisting of three base 64 strings separated by dots
type AccessToken = string

// GUID A unique string representing a user (and given by them)
type GUID = string

// RefreshToken A base64 encoded string used for issuing new pair of tokens
type RefreshToken = string

// TokenPair A pair of access and refresh tokens
type TokenPair struct {
	// AccessToken A JWT Token consisting of three base 64 strings separated by dots
	AccessToken *AccessToken `json:"access_token,omitempty"`

	// RefreshToken A base64 encoded string used for issuing new pair of tokens
	RefreshToken *RefreshToken `json:"refresh_token,omitempty"`
}

// GetGUIDParams defines parameters for GetGUID.
type GetGUIDParams struct {
	// AccessToken User's access token
	AccessToken string `json:"access_token"`
}

// UnauthorizeParams defines parameters for Unauthorize.
type UnauthorizeParams struct {
	// AccessToken User's access token
	AccessToken string `json:"access_token"`
}

// RefreshTokensJSONRequestBody defines body for RefreshTokens for application/json ContentType.
type RefreshTokensJSONRequestBody = TokenPair
