postgres:
  host: localhost
  port: 5433
  database: security_db
  user: security_master
  password: 12345
  max_conn: 15
logger:
  env: dev
  output_paths:
    - stdout
    - log/server.log
  echo_outputs:
    - stdout
    - log/echo.log
port: 443
